[tool]

[tool.poetry]
authors = ["NateuCodes"]
description = "Bug Zero Kata"
name = "root"
version = "0.0.1"

[tool.poetry.dependencies]
python = "^3.8"
approvaltests = "^2.2.0"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
expects = "^0.9.0"
mamba = "^0.11.2"
pytest = "==6.0.0"